### ISSUE TITLE
Author of THREE.FBXLoader here

### ISSUE THREAD

**Issue by looeee** [cs64188/three-fbxloader#1]
Hello! I'm the current maintainer of the THREE.FBXLoader over on the three.js repo. We're currently having issues where a number of users are attempting to use out of date versions of the loader, such as yours, that they have found on NPM. 

If you are not willing to update this regulary (within a day or so of a new three.js version coming out), can you please remove the NPM module and add a note the the readme that this version will be out of date? 

Thank you!

**Comment by cs64188** [comment]
Sorry so long ，I have updated my Readme .
Thank you for your efforts , Threejs will be stronger and stronger !

**Comment by looeee** [comment]
Could you delete this package?

https://www.npmjs.com/package/three-fbxloader-offical
